# -*- coding: utf-8 -*-
"""Thin agent that wraps a :class:`RealtimeModelBase` and exposes its
incoming ``ModelEvents`` as a public ``AgentEvent`` stream.

Unlike :class:`agentscope.agent.Agent`, the realtime agent is bidirectional
and has no request/reply boundary: the caller pushes user audio via
:meth:`send`, while :meth:`event_stream` continuously yields the agent's
events translated from the model's WebSocket frames.

When a :class:`~agentscope.tool.Toolkit` is provided, the agent
automatically executes tool calls returned by the model and sends
results back, similar to the reasoning-acting loop in
:class:`agentscope.agent.Agent`.
"""
import asyncio
import uuid
from asyncio import Queue
from typing import AsyncGenerator, Any

from ._base import RealtimeModelBase
from ._events import ModelEvents
from .._logging import logger
from .._utils._common import _json_loads_with_repair
from ..message import AssistantMsg, UserMsg
from ..tool import ToolChunk, ToolResponse, Toolkit
from ..state import AgentState
from ..event import (
    AgentEvent,
    ConfirmResult,
    DataBlockDeltaEvent,
    DataBlockEndEvent,
    DataBlockStartEvent,
    HintBlockEvent,
    ModelCallEndEvent,
    ModelCallStartEvent,
    ReplyEndEvent,
    ReplyStartEvent,
    RequireUserConfirmEvent,
    TextBlockDeltaEvent,
    TextBlockEndEvent,
    TextBlockStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolResultEndEvent,
    ToolResultStartEvent,
    ToolResultTextDeltaEvent,
    UserConfirmResultEvent,
    UserInputAudioEndEvent,
    UserInputAudioStartEvent,
    UserInputTranscriptionEvent,
)
from ..message import (
    DataBlock,
    TextBlock,
    ToolCallBlock,
    ToolResultBlock,
    ToolResultState,
)
from ..permission import PermissionBehavior, PermissionEngine
from ..types import ErrorInfo, ErrorType, ReplyFinishedReason


class RealtimeAgent:
    """A thin translator between a :class:`RealtimeModelBase` and the public
    :class:`AgentEvent` stream.

    When a :class:`~agentscope.tool.Toolkit` is provided, tool calls from
    the model are automatically executed server-side and results are sent
    back, enabling a full voice-driven tool-use loop.

    Example:

        .. code-block:: python

            async with RealtimeAgent(
                name="Friday",
                model=DashScopeRealtimeModel(...),
                instructions="You are a helpful assistant.",
                toolkit=my_toolkit,
            ) as agent:
                # Drain events in one task...
                async def consume():
                    async for evt in agent.event_stream():
                        print(evt)

                consumer = asyncio.create_task(consume())

                # ...and push input audio in another.
                await agent.send(audio_data_block)

                await consumer
    """

    def __init__(
        self,
        name: str,
        model: RealtimeModelBase,
        instructions: str,
        session_id: str | None = None,
        toolkit: Toolkit | None = None,
        state: "AgentState | None" = None,
    ) -> None:
        """Initialize the realtime agent.

        Args:
            name (`str`):
                Display name of the agent (used in ``ReplyStartEvent.name``).
            model (`RealtimeModelBase`):
                The realtime model client.
            instructions (`str`):
                System instructions forwarded to the model on connect.
            session_id (`str | None`, optional):
                Session id stamped on every emitted event. A new uuid is
                generated if omitted.
            toolkit (`Toolkit | None`, optional):
                The toolkit containing tools available for the realtime
                session. When provided, tool schemas are extracted and
                registered with the model, and tool calls are executed
                automatically.
            state (`AgentState | None`, optional):
                The agent state for storing conversation context and
                tool execution state. A new state is created if omitted.
        """

        self.name = name
        self.model = model
        self.instructions = instructions
        self.session_id = session_id or uuid.uuid4().hex
        self.toolkit = toolkit
        self.state = state or AgentState(session_id=self.session_id)

        self._engine = PermissionEngine(self.state.permission_context)

        self._model_queue: Queue = Queue()
        # Internal queue for events generated by the agent itself
        # (e.g. tool result events from _execute_pending_tool_calls)
        self._internal_event_queue: Queue = Queue()
        # Pending user-confirmation futures: tool_call_id → Future
        self._pending_confirmations: dict[
            str,
            asyncio.Future[ConfirmResult],
        ] = {}
        self._tool_tasks: set[asyncio.Task[None]] = set()
        # Tool calls whose ToolResultStartEvent has been emitted but whose
        # ToolResultEndEvent has not. Used to close the persisted lifecycle
        # cleanly when a realtime connection disappears mid-execution.
        self._started_tool_results: set[str] = set()
        self._finished_tool_results: set[str] = set()
        self._connected = False
        self._tool_schemas: list[dict] | None = None

        # Per-response bookkeeping: response_id (used as reply_id) → block
        # IDs.
        self._audio_blocks: dict[str, str] = {}
        self._text_blocks: dict[str, str] = {}
        self._audio_media_types: dict[str, str] = {}
        # Track active tool call blocks: call_id -> {reply_id, name, arguments}
        self._tool_call_blocks: dict[str, str] = {}
        self._pending_tool_calls: dict[str, dict[str, str]] = {}
        # response_ids for which we have already emitted ReplyStartEvent
        self._started_responses: set[str] = set()
        # Ignore late provider frames after an error or completion has already
        # closed the public reply lifecycle.
        self._closed_responses: set[str] = set()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def __aenter__(self) -> "RealtimeAgent":
        """Enter the async context manager, connecting the session."""
        await self.connect()
        return self

    async def __aexit__(
        self,
        exc_type: type | None,
        exc: Exception | None,
        tb: Any,
    ) -> None:
        """Exit the async context manager, disconnecting the session."""
        await self.disconnect()

    async def connect(self) -> None:
        """Open the underlying realtime model session.

        If the agent state carries a ``session_handle`` from a previous
        connection, it is forwarded to the model so that providers that
        support session resumption (e.g. Gemini) can restore context.
        """
        if self._connected:
            return

        if self.toolkit is not None:
            self._tool_schemas = await self.toolkit.get_tool_schemas()

        connect_kwargs: dict[str, Any] = {}
        if self.state.session_handle:
            connect_kwargs["session_handle"] = self.state.session_handle

        await self.model.connect(
            outgoing_queue=self._model_queue,
            instructions=self.instructions,
            tools=self._tool_schemas,
            **connect_kwargs,
        )
        self._connected = True

    async def disconnect(self) -> None:
        """Close the underlying realtime model session."""
        if not self._connected:
            return
        await self._cancel_tool_tasks()
        await self.model.disconnect()
        self._connected = False

    async def _cancel_tool_tasks(self) -> None:
        """Cancel pending confirmations and detached tool executions."""
        for future in self._pending_confirmations.values():
            if not future.done():
                future.cancel()
        self._pending_confirmations.clear()
        tasks = list(self._tool_tasks)
        for task in tasks:
            task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

    async def interrupt(self) -> None:
        """Interrupt the active provider response.

        Protocols without an in-session cancellation frame close their model
        session. Before doing so, enqueue synthetic completion events so the
        public reply lifecycle still terminates cleanly.
        """
        if not self._connected:
            return
        if self.model.cancel_response_closes_session:
            for reply_id in list(self._started_responses):
                await self._model_queue.put(
                    ModelEvents.ModelResponseDoneEvent(
                        response_id=reply_id,
                        input_tokens=0,
                        output_tokens=0,
                    ),
                )
        await self.model.cancel_response()

    # ------------------------------------------------------------------
    # IO
    # ------------------------------------------------------------------

    async def send(
        self,
        data: DataBlock | TextBlock | ToolResultBlock,
    ) -> None:
        """Forward a content block to the underlying realtime model.

        Args:
            data (`DataBlock | TextBlock | ToolResultBlock`):
                Same semantics as :meth:`RealtimeModelBase.send`.
        """
        await self.model.send(data)

    def handle_user_confirm(
        self,
        event: UserConfirmResultEvent,
    ) -> None:
        """Process a user confirmation for pending tool calls.

        Called by the WebSocket upstream handler when the browser sends
        a ``user_confirm`` frame. Resolves the matching
        :class:`asyncio.Future` so that :meth:`_execute_single_tool_call`
        can proceed.

        Args:
            event (`UserConfirmResultEvent`):
                The event containing one or more confirmation results.
        """
        for result in event.confirm_results:
            future = self._pending_confirmations.get(result.tool_call.id)
            if future is not None and not future.done():
                future.set_result(result)
            else:
                logger.warning(
                    "RealtimeAgent: received confirmation for unknown or "
                    "already-resolved tool_call_id=%s",
                    result.tool_call.id,
                )

    async def event_stream(self) -> AsyncGenerator[AgentEvent, None]:
        """Yield translated :class:`AgentEvent` instances until the session
        ends (model disconnects or caller cancels).

        When a toolkit is present, tool call events trigger automatic
        server-side execution and the result is sent back to the model.
        Tool results are emitted as ``ToolResultStart/TextDelta/End``
        events with the **original** ``reply_id`` so that the consumer
        (frontend) can append them to the already-finished reply message.
        The model's follow-up response arrives as a separate reply.

        User transcriptions and assistant text replies are appended to
        ``self.state.context`` so they can be persisted or inspected.

        Yields:
            `AgentEvent`: Translated agent events (reply lifecycle,
                data blocks, text blocks, tool calls, user transcriptions,
                etc.) in chronological order.
        """

        reply_text_parts: dict[str, list[str]] = {}

        model_waiter: asyncio.Task | None = None
        internal_waiter: asyncio.Task | None = None

        try:
            while True:
                if model_waiter is None:
                    model_waiter = asyncio.create_task(
                        self._model_queue.get(),
                        name="rt-model-get",
                    )
                if internal_waiter is None:
                    internal_waiter = asyncio.create_task(
                        self._internal_event_queue.get(),
                        name="rt-internal-get",
                    )

                done, _ = await asyncio.wait(
                    [model_waiter, internal_waiter],
                    return_when=asyncio.FIRST_COMPLETED,
                )

                events_to_yield: list[AgentEvent] = []
                model_session_ended = False

                if internal_waiter in done:
                    try:
                        internal_evt = internal_waiter.result()
                        events_to_yield.append(internal_evt)
                    except asyncio.CancelledError:
                        pass
                    internal_waiter = None

                if model_waiter in done:
                    try:
                        model_evt = model_waiter.result()
                    except asyncio.CancelledError:
                        return
                    model_waiter = None

                    # Sentinel from _receive_loop: session ended. Internal
                    # cleanup events queued during disconnect still need to
                    # be yielded before the stream terminates.
                    if isinstance(
                        model_evt,
                        ModelEvents.ModelSessionEndedEvent,
                    ):
                        logger.info(
                            "RealtimeAgent: model session ended "
                            "(reason=%s), stopping event_stream",
                            model_evt.reason,
                        )
                        await self._cancel_tool_tasks()
                        model_session_ended = True
                        events_to_yield.extend(
                            self._drain_internal_event_queue(),
                        )
                    else:
                        events_to_yield.extend(self._translate(model_evt))

                for agent_evt in events_to_yield:
                    yield agent_evt

                    # ---- Context storage ----
                    if isinstance(agent_evt, UserInputTranscriptionEvent):
                        if agent_evt.transcript:
                            self.state.context.append(
                                UserMsg(
                                    name="user",
                                    content=agent_evt.transcript,
                                ),
                            )

                    elif isinstance(agent_evt, ReplyStartEvent):
                        self.state.reply_id = agent_evt.reply_id
                        reply_text_parts[agent_evt.reply_id] = []

                    elif isinstance(agent_evt, TextBlockDeltaEvent):
                        if agent_evt.reply_id in reply_text_parts:
                            reply_text_parts[agent_evt.reply_id].append(
                                agent_evt.delta,
                            )

                    elif isinstance(agent_evt, ReplyEndEvent):
                        parts = reply_text_parts.pop(
                            agent_evt.reply_id,
                            None,
                        )
                        if parts:
                            text = "".join(parts)
                            if text.strip():
                                self.state.context.append(
                                    AssistantMsg(
                                        name=self.name,
                                        content=text,
                                        id=agent_evt.reply_id,
                                    ),
                                )

                        # Execute pending tool calls AFTER response.done.
                        # Results are emitted with the original reply_id
                        # so the frontend can append them to this message.
                        if self.toolkit and self._pending_tool_calls:
                            calls = {
                                call_id: info
                                for call_id, info in (
                                    self._pending_tool_calls.items()
                                )
                                if info["reply_id"] == agent_evt.reply_id
                            }
                            for call_id in calls:
                                self._pending_tool_calls.pop(call_id, None)
                            if calls:
                                task = asyncio.create_task(
                                    self._execute_pending_tool_calls(calls),
                                    name=f"rt-tools:{agent_evt.reply_id}",
                                )
                                self._tool_tasks.add(task)
                                task.add_done_callback(
                                    self._tool_tasks.discard,
                                )

                if model_session_ended:
                    return
        except asyncio.CancelledError:
            return
        finally:
            if model_waiter and not model_waiter.done():
                model_waiter.cancel()
            if internal_waiter and not internal_waiter.done():
                internal_waiter.cancel()

    # ------------------------------------------------------------------
    # Internal tool execution
    # ------------------------------------------------------------------

    async def _execute_pending_tool_calls(
        self,
        calls: dict[str, dict[str, str]],
    ) -> None:
        """Execute all pending tool calls and send their results back.

        Per the DashScope protocol, tool results must be sent after
        ``response.done`` and before triggering ``response.create``.
        All results are sent first, then a single ``response.create``
        is issued by the model layer in :meth:`send`.

        This runs as a detached :func:`asyncio.create_task`.
        """
        try:
            completed_call_ids: set[str] = set()
            for call_id, info in calls.items():
                logger.info(
                    "RealtimeAgent: executing tool %s (call_id=%s)",
                    info["name"],
                    call_id,
                )
                await self._execute_single_tool_call(
                    tool_call_id=call_id,
                    tool_name=info["name"],
                    arguments=info["arguments"],
                    reply_id=info["reply_id"],
                )
                completed_call_ids.add(call_id)

            logger.info(
                "RealtimeAgent: all %d tool result(s) sent, "
                "triggering response.create",
                len(calls),
            )
            await self.model.request_response()
            logger.info("RealtimeAgent: request_response sent successfully")
        except asyncio.CancelledError:
            for call_id, info in calls.items():
                if (
                    call_id not in completed_call_ids
                    and call_id not in self._finished_tool_results
                ):
                    await self._emit_interrupted_tool_result(
                        reply_id=info["reply_id"],
                        tool_call_id=call_id,
                        tool_name=info["name"],
                    )
            raise
        except Exception:
            for call_id, info in calls.items():
                if (
                    call_id not in completed_call_ids
                    and call_id not in self._finished_tool_results
                ):
                    await self._emit_interrupted_tool_result(
                        reply_id=info["reply_id"],
                        tool_call_id=call_id,
                        tool_name=info["name"],
                    )
            logger.error(
                "RealtimeAgent: error in _execute_pending_tool_calls",
                exc_info=True,
            )
        finally:
            for call_id in calls:
                self._started_tool_results.discard(call_id)
                self._finished_tool_results.discard(call_id)

    async def _execute_single_tool_call(
        self,
        tool_call_id: str,
        tool_name: str,
        arguments: str,
        reply_id: str | None = None,
    ) -> None:
        """Execute a single tool call with permission checking.

        The lifecycle mirrors :meth:`Agent._execute_tool_call`:

        1. Validate tool availability and parse input.
        2. Check permission via :class:`PermissionEngine`.
        3. If ``ASK`` — emit :class:`RequireUserConfirmEvent`, wait for
           the browser to resolve the pending :class:`asyncio.Future`.
        4. If ``DENY`` — emit an error tool result.
        5. If ``ALLOW`` — execute via the toolkit and stream result events.
        """

        assert self.toolkit is not None

        reply_id = reply_id or self.state.reply_id
        tool_call = ToolCallBlock(
            id=tool_call_id,
            name=tool_name,
            input=arguments,
        )

        # Step 1: validate tool and parse input.
        try:
            tool = await self.toolkit.check_tool_available(
                tool_name,
                self.state.tool_context.activated_groups,
            )
            parsed_input = _json_loads_with_repair(
                arguments,
                tool.input_schema,
            )
        except Exception as exc:
            await self._emit_tool_error(
                reply_id,
                tool_call_id,
                tool_name,
                str(exc),
            )
            return

        # Step 2: check permission.
        decision = await self._engine.check_permission(tool, parsed_input)

        if decision.behavior in (
            PermissionBehavior.ASK,
            PermissionBehavior.PASSTHROUGH,
        ):
            tool_call.suggested_rules = decision.suggested_rules or []
            await self._internal_event_queue.put(
                RequireUserConfirmEvent(
                    reply_id=reply_id,
                    tool_calls=[tool_call],
                ),
            )
            future: asyncio.Future[
                ConfirmResult
            ] = asyncio.get_running_loop().create_future()
            self._pending_confirmations[tool_call_id] = future
            try:
                result = await asyncio.wait_for(future, timeout=300)
            except asyncio.TimeoutError:
                logger.warning(
                    "RealtimeAgent: confirmation timeout for %s",
                    tool_name,
                )
                await self._emit_tool_error(
                    reply_id,
                    tool_call_id,
                    tool_name,
                    "Tool confirmation timed out.",
                    state=ToolResultState.INTERRUPTED,
                )
                return
            finally:
                self._pending_confirmations.pop(tool_call_id, None)

            if not result.confirmed:
                await self._emit_tool_error(
                    reply_id,
                    tool_call_id,
                    tool_name,
                    f'Execution of tool "{tool_name}" denied by user.',
                    state=ToolResultState.DENIED,
                )
                return

            if result.rules:
                for rule in result.rules:
                    self._engine.add_rule(rule)

            tool_call.name = result.tool_call.name
            tool_call.input = result.tool_call.input
            tool_name = result.tool_call.name

        elif decision.behavior == PermissionBehavior.DENY:
            await self._emit_tool_error(
                reply_id,
                tool_call_id,
                tool_name,
                decision.message or f'Tool "{tool_name}" denied by policy.',
                state=ToolResultState.DENIED,
            )
            return

        # Step 3: execute.
        await self._internal_event_queue.put(
            ToolResultStartEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                tool_call_name=tool_name,
            ),
        )
        self._started_tool_results.add(tool_call_id)

        try:
            result_parts: list[str] = []
            final_state = ToolResultState.SUCCESS
            async for chunk in self.toolkit.call_tool(tool_call, self.state):
                if isinstance(chunk, ToolResponse):
                    for block in chunk.content:
                        if isinstance(block, TextBlock):
                            result_parts.append(block.text)
                    final_state = chunk.state
                    break
                if isinstance(chunk, ToolChunk):
                    for block in chunk.content:
                        if isinstance(block, TextBlock):
                            result_parts.append(block.text)
                            await self._internal_event_queue.put(
                                ToolResultTextDeltaEvent(
                                    reply_id=reply_id,
                                    tool_call_id=tool_call_id,
                                    delta=block.text,
                                ),
                            )

            result_text = "".join(result_parts)
            logger.info(
                "RealtimeAgent: tool %s returned: %s",
                tool_name,
                result_text[:200] if result_text else "(empty)",
            )

            await self._internal_event_queue.put(
                ToolResultEndEvent(
                    reply_id=reply_id,
                    tool_call_id=tool_call_id,
                    state=final_state,
                ),
            )
            self._started_tool_results.discard(tool_call_id)
            self._finished_tool_results.add(tool_call_id)

            await self.send(
                ToolResultBlock(
                    id=tool_call_id,
                    name=tool_name,
                    output=result_text or "Tool executed successfully.",
                ),
            )
        except Exception:
            logger.warning(
                "RealtimeAgent: failed to execute tool %s",
                tool_name,
                exc_info=True,
            )
            error_msg = f"Error executing tool {tool_name}."
            await self._internal_event_queue.put(
                ToolResultTextDeltaEvent(
                    reply_id=reply_id,
                    tool_call_id=tool_call_id,
                    delta=error_msg,
                ),
            )
            await self._internal_event_queue.put(
                ToolResultEndEvent(
                    reply_id=reply_id,
                    tool_call_id=tool_call_id,
                    state=ToolResultState.ERROR,
                ),
            )
            self._started_tool_results.discard(tool_call_id)
            self._finished_tool_results.add(tool_call_id)
            await self.send(
                ToolResultBlock(
                    id=tool_call_id,
                    name=tool_name,
                    output=error_msg,
                ),
            )

    async def _emit_tool_error(
        self,
        reply_id: str,
        tool_call_id: str,
        tool_name: str,
        message: str,
        *,
        state: ToolResultState = ToolResultState.ERROR,
    ) -> None:
        """Emit error tool-result events and send the error back to model."""
        await self._internal_event_queue.put(
            ToolResultStartEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                tool_call_name=tool_name,
            ),
        )
        self._started_tool_results.add(tool_call_id)
        await self._internal_event_queue.put(
            ToolResultTextDeltaEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                delta=message,
            ),
        )
        await self._internal_event_queue.put(
            ToolResultEndEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                state=state,
            ),
        )
        self._started_tool_results.discard(tool_call_id)
        self._finished_tool_results.add(tool_call_id)
        await self.send(
            ToolResultBlock(
                id=tool_call_id,
                name=tool_name,
                output=message,
            ),
        )

    async def _emit_interrupted_tool_result(
        self,
        reply_id: str,
        tool_call_id: str,
        tool_name: str,
    ) -> None:
        """Close an unfinished tool-result lifecycle during disconnect."""
        if tool_call_id not in self._started_tool_results:
            await self._internal_event_queue.put(
                ToolResultStartEvent(
                    reply_id=reply_id,
                    tool_call_id=tool_call_id,
                    tool_call_name=tool_name,
                ),
            )
        await self._internal_event_queue.put(
            ToolResultTextDeltaEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                delta="Realtime session disconnected before the tool "
                "call completed.",
            ),
        )
        await self._internal_event_queue.put(
            ToolResultEndEvent(
                reply_id=reply_id,
                tool_call_id=tool_call_id,
                state=ToolResultState.INTERRUPTED,
            ),
        )
        self._started_tool_results.discard(tool_call_id)
        self._finished_tool_results.add(tool_call_id)

    def _drain_internal_event_queue(self) -> list[AgentEvent]:
        """Drain cleanup events already queued before model shutdown."""
        events: list[AgentEvent] = []
        while not self._internal_event_queue.empty():
            events.append(self._internal_event_queue.get_nowait())
        return events

    # ------------------------------------------------------------------
    # Translation
    # ------------------------------------------------------------------

    # pylint: disable=too-many-return-statements
    def _translate(
        self,
        evt: ModelEvents.EventBase,
    ) -> list[AgentEvent]:
        """Map one ``ModelEvents.*`` instance into 0..N ``AgentEvent``s.

        Args:
            evt (`ModelEvents.EventBase`):
                A single model-layer event from the receive queue.

        Returns:
            `list[AgentEvent]`: Zero or more translated agent events
                to yield to the consumer.
        """
        sid = self.session_id

        # ---- Session ----
        if isinstance(evt, ModelEvents.ModelSessionCreatedEvent):
            logger.debug(
                "RealtimeAgent: model session created (id=%s)",
                evt.session_id,
            )
            return []
        if isinstance(evt, ModelEvents.ModelSessionEndedEvent):
            logger.debug(
                "RealtimeAgent: model session ended (reason=%s)",
                evt.reason,
            )
            return []

        # ---- User input / VAD ----
        if isinstance(evt, ModelEvents.ModelInputStartedEvent):
            return [
                UserInputAudioStartEvent(
                    session_id=sid,
                    item_id=evt.item_id,
                    audio_start_ms=evt.audio_start_ms,
                ),
            ]
        if isinstance(evt, ModelEvents.ModelInputDoneEvent):
            return [
                UserInputAudioEndEvent(
                    session_id=sid,
                    item_id=evt.item_id,
                    audio_end_ms=evt.audio_end_ms,
                ),
            ]
        if isinstance(evt, ModelEvents.ModelInputTranscriptionDoneEvent):
            return [
                UserInputTranscriptionEvent(
                    session_id=sid,
                    item_id=evt.item_id,
                    transcript=evt.transcript,
                ),
            ]
        if isinstance(evt, ModelEvents.ModelInputTranscriptionDeltaEvent):
            # No public AgentEvent equivalent for partial input transcripts;
            # the final transcription is emitted via
            # UserInputTranscriptionEvent.
            return []

        # ---- Response lifecycle ----
        response_id = getattr(evt, "response_id", None)
        if response_id and response_id in self._closed_responses:
            logger.debug(
                "RealtimeAgent: ignoring late event for closed response %s",
                response_id,
            )
            return []
        if isinstance(evt, ModelEvents.ModelResponseCreatedEvent):
            reply_id = evt.response_id
            return self._ensure_reply_started(reply_id)
        if isinstance(evt, ModelEvents.ModelResponseDoneEvent):
            reply_id = evt.response_id
            out: list[AgentEvent] = []
            out.extend(self._ensure_reply_started(reply_id))
            out.extend(self._close_text_block(reply_id))
            out.extend(self._close_audio_block(reply_id))
            out.append(
                ModelCallEndEvent(
                    reply_id=reply_id,
                    input_tokens=evt.input_tokens,
                    output_tokens=evt.output_tokens,
                ),
            )
            out.append(
                ReplyEndEvent(session_id=sid, reply_id=reply_id),
            )
            self._started_responses.discard(reply_id)
            self._closed_responses.add(reply_id)
            return out

        # ---- Audio output ----
        if isinstance(evt, ModelEvents.ModelResponseAudioDeltaEvent):
            reply_id = evt.response_id
            media_type = f"{evt.format.type};rate={evt.format.rate}"
            out = []
            out.extend(self._ensure_reply_started(reply_id))
            block_id = self._audio_blocks.get(reply_id)
            if block_id is None:
                block_id = uuid.uuid4().hex
                self._audio_blocks[reply_id] = block_id
                self._audio_media_types[reply_id] = media_type
                out.append(
                    DataBlockStartEvent(
                        reply_id=reply_id,
                        block_id=block_id,
                        media_type=media_type,
                    ),
                )
            out.append(
                DataBlockDeltaEvent(
                    reply_id=reply_id,
                    block_id=block_id,
                    data=evt.delta,
                    media_type=self._audio_media_types[reply_id],
                ),
            )
            return out
        if isinstance(evt, ModelEvents.ModelResponseAudioDoneEvent):
            return self._close_audio_block(evt.response_id)

        # ---- Transcript output ----
        if isinstance(
            evt,
            ModelEvents.ModelResponseAudioTranscriptDeltaEvent,
        ):
            reply_id = evt.response_id
            out = []
            out.extend(self._ensure_reply_started(reply_id))
            block_id = self._text_blocks.get(reply_id)
            if block_id is None:
                block_id = uuid.uuid4().hex
                self._text_blocks[reply_id] = block_id
                out.append(
                    TextBlockStartEvent(
                        reply_id=reply_id,
                        block_id=block_id,
                    ),
                )
            out.append(
                TextBlockDeltaEvent(
                    reply_id=reply_id,
                    block_id=block_id,
                    delta=evt.delta,
                ),
            )
            return out
        if isinstance(
            evt,
            ModelEvents.ModelResponseAudioTranscriptDoneEvent,
        ):
            return self._close_text_block(evt.response_id)

        # ---- Tool calls ----
        if isinstance(evt, ModelEvents.ModelResponseToolCallDeltaEvent):
            reply_id = evt.response_id
            call_id = evt.tool_call.id
            out = []
            out.extend(self._ensure_reply_started(reply_id))
            if call_id not in self._tool_call_blocks:
                self._tool_call_blocks[call_id] = reply_id
                self._pending_tool_calls[call_id] = {
                    "name": evt.tool_call.name,
                    "arguments": "",
                    "reply_id": reply_id,
                }
                out.append(
                    ToolCallStartEvent(
                        reply_id=reply_id,
                        tool_call_id=call_id,
                        tool_call_name=evt.tool_call.name,
                    ),
                )
            # evt.tool_call.input is an incremental delta fragment
            if call_id in self._pending_tool_calls:
                self._pending_tool_calls[call_id][
                    "arguments"
                ] += evt.tool_call.input
            out.append(
                ToolCallDeltaEvent(
                    reply_id=reply_id,
                    tool_call_id=call_id,
                    delta=evt.tool_call.input,
                ),
            )
            return out
        if isinstance(evt, ModelEvents.ModelResponseToolCallDoneEvent):
            reply_id = evt.response_id
            call_id = evt.tool_call.id
            out = []
            out.extend(self._ensure_reply_started(reply_id))
            if call_id not in self._tool_call_blocks:
                self._tool_call_blocks[call_id] = reply_id
                self._pending_tool_calls[call_id] = {
                    "name": evt.tool_call.name,
                    "arguments": "",
                    "reply_id": reply_id,
                }
                out.append(
                    ToolCallStartEvent(
                        reply_id=reply_id,
                        tool_call_id=call_id,
                        tool_call_name=evt.tool_call.name,
                    ),
                )
            # The done event carries the authoritative name and full
            # argument string; always update pending_tool_calls.
            if call_id in self._pending_tool_calls:
                if evt.tool_call.name:
                    self._pending_tool_calls[call_id][
                        "name"
                    ] = evt.tool_call.name
                self._pending_tool_calls[call_id][
                    "arguments"
                ] = evt.tool_call.input
            out.append(
                ToolCallEndEvent(
                    reply_id=reply_id,
                    tool_call_id=call_id,
                ),
            )
            self._tool_call_blocks.pop(call_id, None)
            return out

        # ---- Session resumption ----
        if isinstance(evt, ModelEvents.ModelSessionResumptionEvent):
            self.state.session_handle = evt.handle
            logger.debug(
                "RealtimeAgent: session resumption handle updated",
            )
            return []

        # ---- Error ----
        if isinstance(evt, ModelEvents.ModelErrorEvent):
            logger.error(
                "RealtimeAgent: model error %s/%s: %s",
                evt.error_type,
                evt.code,
                evt.message,
            )
            # Surface the error to the client as a HintBlock so users
            # can see what went wrong without checking server logs.
            active_reply_id: str | None = None
            if self.state.reply_id in self._started_responses:
                active_reply_id = self.state.reply_id
            elif self._started_responses:
                active_reply_id = next(iter(self._started_responses))
            reply_id = active_reply_id or uuid.uuid4().hex
            events: list[AgentEvent] = self._ensure_reply_started(reply_id)
            events.extend(self._close_text_block(reply_id))
            events.extend(self._close_audio_block(reply_id))
            events.append(
                HintBlockEvent(
                    session_id=self.session_id,
                    reply_id=reply_id,
                    block_id=uuid.uuid4().hex,
                    source="system",
                    hint=f"[Model Error] {evt.error_type}/{evt.code}: "
                    f"{evt.message}",
                ),
            )
            events.append(
                ModelCallEndEvent(
                    reply_id=reply_id,
                    input_tokens=0,
                    output_tokens=0,
                ),
            )
            events.append(
                ReplyEndEvent(
                    session_id=sid,
                    reply_id=reply_id,
                    finished_reason=ReplyFinishedReason.ERROR,
                    error=ErrorInfo(
                        type=ErrorType.UNKNOWN,
                        message=f"{evt.error_type}/{evt.code}: {evt.message}",
                    ),
                ),
            )
            self._started_responses.discard(reply_id)
            self._closed_responses.add(reply_id)
            return events

        logger.debug(
            "RealtimeAgent: unhandled model event %s",
            type(evt).__name__,
        )
        return []

    # ------------------------------------------------------------------
    # Block close helpers
    # ------------------------------------------------------------------

    def _ensure_reply_started(self, reply_id: str) -> list[AgentEvent]:
        """Emit ``ReplyStartEvent`` + ``ModelCallStartEvent`` for *reply_id*
        if we haven't done so yet.

        This covers providers (e.g. ElevenLabs) that never send an
        explicit ``response.created`` frame.

        Args:
            reply_id (`str`): The response/reply identifier.

        Returns:
            `list[AgentEvent]`: A pair of start events on first call for
                a given *reply_id*, or empty on subsequent calls.
        """
        if reply_id in self._started_responses:
            return []
        self._started_responses.add(reply_id)
        return [
            ReplyStartEvent(
                session_id=self.session_id,
                reply_id=reply_id,
                name=self.name,
            ),
            ModelCallStartEvent(
                reply_id=reply_id,
                model_name=self.model.model_name,
            ),
        ]

    def _close_audio_block(self, reply_id: str) -> list[AgentEvent]:
        """Emit ``DataBlockEndEvent`` for the open audio block (if any).

        Args:
            reply_id (`str`): The reply ID whose audio block to close.

        Returns:
            `list[AgentEvent]`: A list with one ``DataBlockEndEvent``,
                or empty if no open audio block existed for *reply_id*.
        """
        block_id = self._audio_blocks.pop(reply_id, None)
        self._audio_media_types.pop(reply_id, None)
        if block_id is None:
            return []
        return [DataBlockEndEvent(reply_id=reply_id, block_id=block_id)]

    def _close_text_block(self, reply_id: str) -> list[AgentEvent]:
        """Emit ``TextBlockEndEvent`` for the open text block (if any).

        Args:
            reply_id (`str`): The reply ID whose text block to close.

        Returns:
            `list[AgentEvent]`: A list with one ``TextBlockEndEvent``,
                or empty if no open text block existed for *reply_id*.
        """
        block_id = self._text_blocks.pop(reply_id, None)
        if block_id is None:
            return []
        return [TextBlockEndEvent(reply_id=reply_id, block_id=block_id)]
